// =======================================================
// src/vic/graphics_mode_transition.rs — Mid-line graphical mode transition pixel output - Handles the pixel pipeline correction when ECM/BMM changes during an active
// =======================================================

use super::state::VicII;
use super::fsm::GraphicsMode;
use super::foreground::{ForegroundCell, PixelSpan};
use super::foreground_transition::render_foreground_span;

/*
Graphics-mode writes can occur while an eight-pixel cell is being shifted. The transition code determines which pixels retain the old interpretation and which are decoded with the new ECM/BMM/MCM combination rather than applying the new mode to the whole cell retroactively.
*/
/* Mid-cell mode changes cannot be modelled by selecting one renderer for the entire character. These helpers divide the eight-pixel cell at the exact write position and preserve the foreground mask generated by each side of the transition. */
impl VicII {
	pub(super) fn apply_graphics_mode_transition(&mut self, mode_old: GraphicsMode, mode_new: GraphicsMode, old_horizontal_scroll: u8, cycle: u16) {
		self.pixels_to_skip = 0;

		let gfx_data2  = self.graphics_data_fetched;
		let gfx_data1  = self.graphics_data_pipeline_1;
		let char_data1 = self.char_data_pipeline_1;
		let char_data2 = self.char_data_fetched;

		let bmm_old = mode_old.bitmap_bit();
		let bmm_new = mode_new.bitmap_bit();
		let mcm = mode_old.multicolour_bit();

		let (wide_1, wide_2, mc_route_1, mc_route_2) =
			Self::resolve_mcm_routes(mcm, bmm_old, bmm_new, old_horizontal_scroll, char_data1, char_data2);

		let force_single_1 = !wide_1;
		let force_single_2 = !wide_2;

		let mut gfx_data1_t = gfx_data1;
		let mut gfx_data2_t = gfx_data2;

		if wide_1 && !mc_route_1 {
			let t       = gfx_data1 & 0xAA;
			gfx_data1_t = t | (t >> 1);
		}
		if wide_2 && !mc_route_2 {
			let t       = gfx_data2 & 0xAA;
			gfx_data2_t = t | (t >> 1);
		}

		/*
		The transition table is indexed by the two mode bits that change the physical interpretation of the shifter path. Keeping the old and new halves in one compact selector makes every mixed cell deterministic without re-reading live registers.
		*/
		let case_sel = ((mode_old.code() << 1) & 0x0C) | ((mode_new.code() >> 1) & 0x03);
		let cdod     = self.border.char_data_output_disabled;
		let skip_ref = &mut self.pixels_to_skip;
		let screen   = &mut self.screen;

		match case_sel {
			0 | 5 | 10 | 15 => {}
			1 | 3 | 11 => {
				render_foreground_span(screen, ForegroundCell::new(gfx_data1_t, 0, char_data1, mode_new, force_single_1 as u8, cdod, cycle + 1), PixelSpan::new(8 - old_horizontal_scroll, old_horizontal_scroll), skip_ref);
				render_foreground_span(screen, ForegroundCell::new(gfx_data2_t, old_horizontal_scroll as i8, char_data2, mode_new, force_single_2 as u8, cdod, cycle + 1), PixelSpan::new(0, 8), skip_ref);
				*skip_ref = 8;
			}
			2 | 7 => {
				render_foreground_span(screen, ForegroundCell::new(gfx_data1_t, 0, char_data1, mode_new, 0, cdod, cycle + 1), PixelSpan::new(8 - old_horizontal_scroll, old_horizontal_scroll), skip_ref);
				*skip_ref = 0;
			}
			4 | 6 | 14 => {
				if old_horizontal_scroll == 0 {
					render_foreground_span(screen, ForegroundCell::new(gfx_data2, 0, char_data2, GraphicsMode::from_code(mode_new.code() | 2), 0, cdod, cycle + 1), PixelSpan::new(0, 1), skip_ref);
					render_foreground_span(screen, ForegroundCell::new(gfx_data2_t, 1, char_data2, mode_new, force_single_2 as u8, cdod, cycle + 1), PixelSpan::new(1, 7), skip_ref);
					*skip_ref = 8;
				} else {
					render_foreground_span(screen, ForegroundCell::new(gfx_data1, 0, char_data1, GraphicsMode::from_code(mode_new.code() | 2), 0, cdod, cycle + 1), PixelSpan::new(8 - old_horizontal_scroll, 1), skip_ref);
					render_foreground_span(screen, ForegroundCell::new(gfx_data1_t, 1, char_data1, mode_new, 0, cdod, cycle + 1), PixelSpan::new(8 - old_horizontal_scroll + 1, old_horizontal_scroll - 1), skip_ref);
					render_foreground_span(screen, ForegroundCell::new(gfx_data2_t, old_horizontal_scroll as i8, char_data2, mode_new, force_single_2 as u8, cdod, cycle + 1), PixelSpan::new(0, 8), skip_ref);
					*skip_ref = 8;
				}
			}
			8 | 13 => {
				if old_horizontal_scroll == 0 {
					render_foreground_span(screen, ForegroundCell::new(gfx_data2, 0, char_data2, GraphicsMode::from_code(mode_new.code() | 4), 0, cdod, cycle + 1), PixelSpan::new(0, 1), skip_ref);
					*skip_ref = 1;
				} else {
					render_foreground_span(screen, ForegroundCell::new(gfx_data1, 0, char_data1, GraphicsMode::from_code(mode_new.code() | 4), 0, cdod, cycle + 1), PixelSpan::new(8 - old_horizontal_scroll, 1), skip_ref);
					render_foreground_span(screen, ForegroundCell::new(gfx_data1, 1, char_data1, mode_new, 0, cdod, cycle + 1), PixelSpan::new(8 - old_horizontal_scroll + 1, old_horizontal_scroll - 1), skip_ref);
					*skip_ref = 0;
				}
			}
			9 => {
				if old_horizontal_scroll == 0 {
					render_foreground_span(screen, ForegroundCell::new(gfx_data2_t, 0, char_data2, GraphicsMode::from_code(mode_new.code() | 4), 0, cdod, cycle + 1), PixelSpan::new(0, 1), skip_ref);
					render_foreground_span(screen, ForegroundCell::new(gfx_data2_t, 1, char_data2, mode_new, force_single_2 as u8, cdod, cycle + 1), PixelSpan::new(1, 7), skip_ref);
					*skip_ref = 8;
				} else {
					render_foreground_span(screen, ForegroundCell::new(gfx_data1_t, 0, char_data1, GraphicsMode::from_code(mode_new.code() | 4), 0, cdod, cycle + 1), PixelSpan::new(8 - old_horizontal_scroll, 1), skip_ref);
					render_foreground_span(screen, ForegroundCell::new(gfx_data1_t, 1, char_data1, mode_new, 0, cdod, cycle + 1), PixelSpan::new(8 - old_horizontal_scroll + 1, old_horizontal_scroll - 1), skip_ref);
					render_foreground_span(screen, ForegroundCell::new(gfx_data2_t, old_horizontal_scroll as i8, char_data2, mode_new, force_single_2 as u8, cdod, cycle + 1), PixelSpan::new(0, 8), skip_ref);
					*skip_ref = 8;
				}
			}
			12 => {
				if old_horizontal_scroll == 0 {
					render_foreground_span(screen, ForegroundCell::new(gfx_data2, 0, char_data2, GraphicsMode::from_code(mode_new.code() | 6), 0, cdod, cycle + 1), PixelSpan::new(0, 1), skip_ref);
					render_foreground_span(screen, ForegroundCell::new(gfx_data2_t, 1, char_data2, mode_new, force_single_2 as u8, cdod, cycle + 1), PixelSpan::new(1, 7), skip_ref);
					*skip_ref = 8;
				} else {
					render_foreground_span(screen, ForegroundCell::new(gfx_data1_t, 0, char_data1, GraphicsMode::from_code(mode_new.code() | 6), 0, cdod, cycle + 1), PixelSpan::new(8 - old_horizontal_scroll, 1), skip_ref);
					render_foreground_span(screen, ForegroundCell::new(gfx_data1_t, 1, char_data1, mode_new, 0, cdod, cycle + 1), PixelSpan::new(8 - old_horizontal_scroll + 1, old_horizontal_scroll - 1), skip_ref);
					render_foreground_span(screen, ForegroundCell::new(gfx_data2_t, old_horizontal_scroll as i8, char_data2, mode_new, force_single_2 as u8, cdod, cycle + 1), PixelSpan::new(0, 8), skip_ref);
					*skip_ref = 8;
				}
			}
			_ => {}
		}
	}

	/*
	A bitmap-mode transition changes which latch supplies the multicolour decision. The returned pairs distinguish symbol width from the route that interprets paired bits, because a cell can temporarily retain wide timing while taking colour selection from the neighbouring character latch.
	*/
	fn resolve_mcm_routes(mcm: bool, bmm_old: bool, bmm_new: bool, old_horizontal_scroll: u8, char_data1: u16, char_data2: u16) -> (bool, bool, bool, bool) {
		if bmm_old && !bmm_new {
			let wide_1     = mcm;
			let mc_route_1 = mcm && (char_data1 & 0x800) != 0;
			let (wide_2, mc_route_2) = if old_horizontal_scroll > 4 {
				(mcm && (char_data2 & 0x800) != 0, mcm && (char_data2 & 0x800) != 0)
			} else {
				(mcm, mcm && (char_data2 & 0x800) != 0)
			};
			(wide_1, wide_2, mc_route_1, mc_route_2)
		} else if !bmm_old && bmm_new {
			let wide_1     = mcm && (char_data1 & 0x800) != 0;
			let mc_route_1 = mcm;
			let (wide_2, mc_route_2) = if old_horizontal_scroll >= 4 {
				(mcm, mcm)
			} else {
				(mcm && (char_data2 & 0x800) != 0, mcm)
			};
			(wide_1, wide_2, mc_route_1, mc_route_2)
		} else if bmm_old {
			(mcm, mcm, mcm, mcm)
		} else {
			let wide_1 = mcm && (char_data1 & 0x800) != 0;
			let wide_2 = mcm && (char_data2 & 0x800) != 0;
			(wide_1, wide_2, wide_1, wide_2)
		}
	}
}